### ISSUE TITLE
unable to locate file inf2cat.exe

### ISSUE THREAD

**Issue by tobycroft** [riverar/Remove-HypervisorChecks#3]
+     Start-Process -FilePath inf2cat.exe -Wait -ArgumentList @(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process]，InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

**Comment by tobycroft** [comment]
I am using it under 451.67 as required

**Comment by tobycroft** [comment]
btw WDK and EWDK is already installed I means if inf2cat.exe is needed, where should I pasted that in by manually?

**Comment by riverar** [comment]
Sorry for the confusion, I should add better notes to the `README`. You need to open an EWDK shell before executing the PowerShell. See https://www.withinrafael.com/2020/06/06/how-to-get-consumer-gpus-working-in-hyperv-virtual-machines/ for more details (bottom of the page).

**Comment by tobycroft** [comment]
I've read that blog for more than 10 times LOL.

I would like to passthrough my GTX750 to VM ,incase of get error somehow.

could you please share your patched file ?

**Comment by tobycroft** [comment]
And there is a issue , I've only got 1803, is there any possible to run EWDK?

**Comment by riverar** [comment]
The EWDK ISO is standalone, you don't need to install it or anything. Should work fine on 1803 but if not, here's the EWDK for 1803 https://go.microsoft.com/fwlink/?linkid=873060.

**Comment by tobycroft** [comment]
can I just install WDK instead?

**Comment by riverar** [comment]
That could work too, but it usually integrates with Visual Studio and generally makes a mess on disk.

**Comment by tobycroft** [comment]
> That could work too, but it usually integrates with Visual Studio and generally makes a mess on disk.

and btw if I choose to use CUDA under Linux ,do I still need to patch this kinda of driver after DDA?

**Comment by tobycroft** [comment]
![image](https://user-images.githubusercontent.com/24893075/98239434-ec9ff100-1fa2-11eb-8dcc-8d3da59d6d4a.png)
![image](https://user-images.githubusercontent.com/24893075/98239477-f88bb300-1fa2-11eb-9f63-edd4087353c7.png)

**Comment by tobycroft** [comment]
![image](https://user-images.githubusercontent.com/24893075/98240200-05f56d00-1fa4-11eb-99d6-87988f7f5fe8.png)

if I execute like the blog does,it will be like this.....

it will open a not pad and shown this, if I just execute the cmd. and open a powershell,it will be like before

what did it wrong.

'.'is not an internal or external command, nor a runnable program

**Comment by tobycroft** [comment]
Holy it works!!!

Really thanks!
