### ISSUE TITLE
0x800f0247 - A problem was encountered while attempting to add the driver to the store.

### ISSUE THREAD

**Issue by vanatom** [riverar/Remove-HypervisorChecks#4]
I followed your guide to a T...

I have a GT 710 in an HP ML350p Gen8. All required CPU features enabled. Server 2019 Hyper-V host, Windows 10 guest. Secure boot is disabled on the VM. I am working with the latest GeForce driver support by your script, 451.67.

The driver patching process was successful. The error occurs during installation. I have tried running setup.exe (see attached log file) and I've also tried using Device Manager to update driver and point it to the Display.Driver folder. Both methods give the same error.

I originally tried this on Win10 20H2. Thinking maybe it was a compatibility issue with the latest build, I tried it on Win10 1909 and got the same error. Any ideas? Could this maybe be a signing issue?

Merry Christmas! Definitely no rush. :)

[Log.7792setup.exe.log](https://github.com/riverar/Remove-HypervisorChecks/files/5740591/Log.7792setup.exe.log)

**Comment by riverar** [comment]
@vanatom Might be an issue with the latest patch (was contributor provided), let me re-run a test here and get back to you tonight.

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/103123411-1daeb080-4639-11eb-8c64-97d6980948ba.png)

@vanatom Still testing. It appears to be working but am running into some virtual machine instability at the moment. Haven't used this in a while so I need to go through and verify some settings.

Are you running setup in a guest machine with Test Mode enabled? (`bcdedit /set TESTSIGNING on`)

**Comment by vanatom** [comment]
I did not! That did the trick! After telling it to install anyway and a reboot, it's working now. Thank you!!!

Do I need to leave test mode on or can I turn it off after installing?

**Comment by riverar** [comment]
Has to remain on as we're not using proper certs, sadly. But should have no discernible impact to performance, etc.

I'll add a step to the docs to make this clearer, thanks for the big report!

**Comment by riverar** [comment]
Added parenthetical to §**Patch graphic card drivers**, step 5 to clarify test mode requirement. Site will automatically update shortly.
