### ISSUE TITLE
Issue on Quadro Drivers

### ISSUE THREAD

**Issue by RoroTitiFR** [riverar/Remove-HypervisorChecks#5]
Hello,

I successfully applied the patch on corresponding Quadro Drivers release (release 441.77) and I noticed that even if the bytes are identical, the patch doesn't work with these drivers (still 43 error code).

I tried the manual patch method (described here: https://github.com/MicrosoftDocs/windowsserverdocs/issues/3083#issuecomment-591815900) with no more luck...

Any advice about that ?

**Comment by riverar** [comment]
@RoroTiti Two things
* There's a new patch I just merged in, check it out
* NVIDIA just announced new drivers that need no patching! https://nvidia.custhelp.com/app/answers/detail/a_id/5173/~/geforce-gpu-passthrough-for-windows-virtual-machine-%28beta%29

Going to close this. Feel free to re-open if you continue to have trouble.
