### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by troymroberts** [riverar/Remove-HypervisorChecks#7]
When i attempt to run it against a drive package i get the following error

Remove-HypervisorChecks
Copyright(c) 2020 Rafael Rivera
https://withinrafael.com

[+] Staging 7-Zip...
[+] Extracting c:\Temp\462.exe...
[+] Expanding C:\temp\Tools\Temp\Extracted\Display.Driver\nvlddmkm.sy_...
[+] Looking for target byte pattern...
[+] Found @ 1632607.
[+] Patching C:\temp\Tools\Temp\Extracted\Display.Driver\nvlddmkm.sys...
[+] Patched.
[+] Compressing C:\temp\Tools\Temp\Extracted\Display.Driver\nvlddmkm.sys...
[+] Rebuilding driver package (this will take a few minutes)...
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\temp\Remove-HypervisorChecks.ps1:148 char:5
+     Start-Process -FilePath inf2cat.exe -Wait -ArgumentList @(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

**Comment by pschaub** [comment]
You should use [EWDK](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#enterprise-wdk-ewdk-for-windows-10-version-2004). See https://github.com/riverar/Remove-HypervisorChecks/issues/3

**Comment by riverar** [comment]
Per the blog post:
![image](https://user-images.githubusercontent.com/475132/120054723-70c0d100-bfe6-11eb-8c09-5beceac6fd54.png)

Apologies if that wasn't clear. Going to close this, but feel free to re-open if you continue to have issues.
